name: Build Tauri App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install  # 或 npm install
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Build Tauri App (x86_64)
        run: |
          cd src-tauri
          cargo install tauri-cli
          cargo tauri build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cd src-tauri-${{ runner.os }}-${{ runner.arch }}
          path: src-tauri/target/release/bundle/dmg/cd src-tauri_0.1.0_x64.dmg

  build_macos_m2:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install  # 或 npm install
      - name: Install Rust and target for ARM64
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add aarch64-apple-darwin
      - name: Build Tauri App (ARM64)
        run: |
          cd src-tauri
          cargo install tauri-cli
          cargo tauri build --target aarch64-apple-darwin
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cd src-tauri-${{ runner.os }}-aarch64
          path: target/aarch64-apple-darwin/release/bundle/dmg/cd src-tauri_0.1.0_aarch64.dmg

  build_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install  # 或 npm install
      - name: Install dependencies for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev build-essential libappindicator3-dev libssl-dev libdbus-1-dev squashfs-tools

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build Tauri App
        run: |
          cd src-tauri
          cargo install tauri-cli
          cargo tauri build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cd src-tauri-${{ runner.os }}-${{ runner.arch }}-deb
          path: target/release/bundle/deb/cd src-tauri_0.1.0_amd64.deb

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cd src-tauri-${{ runner.os }}-${{ runner.arch }}-appimage
          path: target/release/bundle/appimage/cd src-tauri_0.1.0_amd64.AppImage


  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install  # 或 npm install
      - name: Install Rust
        run: |
          choco install rustup.install
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$USERPROFILE\\.cargo\\bin" >> $GITHUB_PATH
      - name: Build Tauri App
        run: |
          cd src-tauri
          cargo install tauri-cli
          cargo tauri build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cd src-tauri-${{ runner.os }}-${{ runner.arch }}
          path: target/release/bundle/msi/cd src-tauri_0.1.0_x64_en-US.msi